name: Test Exercises

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Test Exercises
        run: |
          set -o pipefail
          xcodebuild test \
            -project xcodeProject/ObjectiveC.xcodeproj \
            -scheme xobjectivecTest \
            -destination 'platform=macOS' \
            | xcpretty
